Revert "Remove redundant install of pip, wheel, setuptools"
This reverts commit 5cce3b76ad105c6bf1b9acd186e979bcba5da5a3, as it
broke the service:

```
  File "/usr/local/lib/python2.7/dist-packages/extended_choices/__init__.py", line 6, in <module>
    from setuptools.config import read_configuration
ImportError: No module named config
```